version: "3.8"

services:
  sql-server-kasbotech:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-kasbotech
    hostname: sql-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Mehran@SQRootPass
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - db

volumes:
  sqldb:
  sqlserver_data:
networks:
  db:
    driver: bridge
